export const LABEL = {
  EMAIL: 'Email',
  PASSWORD: 'Password',
  PLACEHOLDER: {
    EMAIL: 'Enter your email',
    PASSWORD: 'Enter your password',
    SEARCH_BY_NAME_OR_ADMISSION_NO: 'Search by name or admission number',
    AUTO_GENERATED: 'AUTO-GENERATED',
    SEARCH_GUARDIAN_NAME: 'Search guardian name...',
    OPTIONAL: 'Optional',
  },
  BUTTON: {
    LOGIN: 'Login',
    FORGOT_PASSWORD: 'Forgot Password',
    PASSWORD_RESET_LINK: 'Send Reset Link',
    BACK_TO_LOGIN: 'Back to Login',
    ADD_STUDENT: 'Add Student',
    BULK_IMPORT: 'Bulk Import',
    BULK_UPDATE: 'Bulk Update',
    VIEW_PROFILE: 'View Profile',
    EDIT: 'Edit',
    DELETE: 'Delete',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    CLEAR_ALL: 'Clear All',
    UPLOAD_DOCUMENT: 'Upload Document',
  },
  MESSAGE: {
    UNSAVED_CHANGES: 'You have unsaved changes. Are you sure you want to close?',
  },
  HEADER: {
    SCHOOL_LOGIN: 'SCHOOL LOGIN',
    FORGOT_PASSWORD: 'FORGOT PASSWORD',
    STUDENT: 'Students',
  },
  SELECT_BOX: {
    SELECT_CLASS: 'Select Class',
    SELECT_SECTION: 'Select Section',
    SELECT_GENDER: 'Select Gender',
    SELECT_STATUS: 'Select Status',
  },
  OPTIONS: {
    STATUS: [
      { value: 1, label: 'Active' },
      { value: 0, label: 'Inactive' },
    ],
    GENDER: [
      { value: 'MALE', label: 'Male' },
      { value: 'FEMALE', label: 'Female' },
    ],
    // 
  },
  ADMISSION_NO: 'Admission No',
  NAME: 'Name',
  CLASS_AND_SECTION: 'Class / Section',
  DOB: 'Date of Birth',
  GENDER: 'Gender',
  GUARDIAN: 'Guardian',
  PHONE: 'Phone',
  STATUS: 'Status',
  ACTIONS: 'Actions',
  NOTE: {
    SELECT_AT_LEAST_ONE_STUDENT: 'Please select at least one student for bulk actions.',
    ADMISSION_NO_IS_PERMANENT: 'Admission No is permanent once saved',
  },
  CLASS: 'Class',
  SECTION: 'Section',
  ADMISSION_YEAR: 'Admission Year',
  SEARCH: 'Search',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  NO_STUDENT_FOUND: 'No students found.',
  FIRST_NAME: 'First Name',
  MIDDLE_NAME: 'Middle Name',
  LAST_NAME: 'Last Name',
  ADD_STUDENT: 'Add Student',
  EDIT_STUDENT: 'Edit Student',
  GUARDIAN_NAME: 'Guardian Name',
  STUDENT_EMAIL: 'Student Email',
  TEMP_PASSWORD: 'Temp Password',
  NOTE_LABEL: 'Note',
  CONTACT_NUMBER: 'Contact Number',
  ADDRESS: 'Address',
  OVERVIEW: 'Overview',
  ACADEMIC_HISTORY: 'Academic History',
  ATTENDANCE:' Attendance',
  EXAMS: 'Exams',
  FEES: 'Fees',
  DOCUMENTS: 'Documents',
  TIMELINE: 'Timeline',
  HEALTH: 'Health',
  DOCUMENTS: 'Documents',
  STUDENT_PROFILE: 'Student Profile',
  ACADEMIC_YEAR: 'Academic Year',
};