export const LABEL = {
  TITLE: 'Weekly Dev',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  PLACEHOLDER: {
    EMAIL: 'Enter your email',
    PASSWORD: 'Enter your password',
    SEARCH_BY_NAME_OR_ADMISSION_NO: 'Search by name or admission number',
    AUTO_GENERATED: 'AUTO-GENERATED',
    SEARCH_GUARDIAN_NAME: 'Search guardian name...',
    OPTIONAL: 'Optional',
    SEARCH_BY_NAME_OR_EMPLOYEE_NO: 'Search by name or employee number',
  },
  BUTTON: {
    LOGIN: 'Login',
    FORGOT_PASSWORD: 'Forgot Password',
    PASSWORD_RESET_LINK: 'Send Reset Link',
    BACK_TO_LOGIN: 'Back to Login',
    ADD_STUDENT: 'Add Student',
    BULK_IMPORT: 'Bulk Import',
    BULK_UPDATE: 'Bulk Update',
    VIEW_PROFILE: 'View Profile',
    EDIT: 'Edit',
    DELETE: 'Delete',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    CLEAR_ALL: 'Clear All',
    UPLOAD_DOCUMENT: 'Upload Document',
    IMPORT: 'Import',
    CONFIRM: 'Confirm',
    ADD_TEACHER: 'Add Teacher',
    DELETE_SELECTED: 'Delete Selected',
    LOGOUT: 'Logout',
  },
  MESSAGE: {
    UNSAVED_CHANGES: 'You have unsaved changes. Are you sure you want to close?',
  },
  HEADER: {
    SCHOOL_LOGIN: 'SCHOOL LOGIN',
    FORGOT_PASSWORD: 'FORGOT PASSWORD',
    STUDENT: 'Students',
  },
  SELECT_BOX: {
    SELECT_CLASS: 'Select Class',
    SELECT_SECTION: 'Select Section',
    SELECT_GENDER: 'Select Gender',
    SELECT_STATUS: 'Select Status',
    SELECT_SUBJECT: 'Select Subject',
    SELECT_ACADEMIC_YEAR: 'Select Academic Year',
    SELECT_SUBJECT: 'Select Subject',
  },
  OPTIONS: {
    STATUS: [
      { value: 1, label: 'Active' },
      { value: 0, label: 'Inactive' },
    ],
    GENDER: [
      { value: 'MALE', label: 'Male' },
      { value: 'FEMALE', label: 'Female' },
    ],
    // 
  },
  ADMISSION_NO: 'Admission No',
  NAME: 'Name',
  CLASS_AND_SECTION: 'Class / Section',
  DOB: 'Date of Birth',
  GENDER: 'Gender',
  GUARDIAN: 'Guardian',
  PHONE: 'Phone',
  STATUS: 'Status',
  ACTIONS: 'Actions',
  NOTE: {
    SELECT_AT_LEAST_ONE_STUDENT: 'Please select at least one student for bulk actions.',
    ADMISSION_NO_IS_PERMANENT: 'Admission No is permanent once saved',
    UPLOAD_CSV_PREVIEW: 'Upload a CSV or Excel file to preview before importing.',
    MAX_SIZE_5_MB: 'Max size 5MB. Use the provided template for best results.',
    CHOOSE_A_FILE_OR_DRAG: 'Choose file or drag it here',
    ACCEPTED_CSV_XLSX: 'Accepted: .csv, .xlsx',
    PLEASE_CONFIRM_BEFORE_PROCEEDING: 'Please confirm before proceeding.',
    THIS_WILL_DELETE_STUDENT: 'This will permanently delete the student. Continue?',
    DELETE_SELECTED_STUDENTS: 'Delete selected students?',
    NO_CLASS_ASSIGNMENT: 'No class assignment',
    TEACHER_ASSIGN_MULTIPLE_CLASSES: 'A teacher can be assigned to multiple classes.',
  },
  CLASS: 'Class',
  SECTION: 'Section',
  ADMISSION_YEAR: 'Admission Year',
  SEARCH: 'Search',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  NO_STUDENT_FOUND: 'No students found.',
  NO_TEACHER_FOUND: 'No teachers found.',
  FIRST_NAME: 'First Name',
  MIDDLE_NAME: 'Middle Name',
  LAST_NAME: 'Last Name',
  ADD_STUDENT: 'Add Student',
  EDIT_STUDENT: 'Edit Student',
  GUARDIAN_NAME: 'Guardian Name',
  STUDENT_EMAIL: 'Student Email',
  TEMP_PASSWORD: 'Temp Password',
  NOTE_LABEL: 'Note',
  CONTACT_NUMBER: 'Contact Number',
  ADDRESS: 'Address',
  OVERVIEW: 'Overview',
  ACADEMIC_HISTORY: 'Academic History',
  ATTENDANCE:' Attendance',
  EXAMS: 'Exams',
  FEES: 'Fees',
  DOCUMENTS: 'Documents',
  TIMELINE: 'Timeline',
  HEALTH: 'Health',
  DOCUMENTS: 'Documents',
  STUDENT_PROFILE: 'Student Profile',
  ACADEMIC_YEAR: 'Academic Year',
  BULK_IMPORT_PREVIEW: 'Bulk Import Preview',
  IMPORT_STUDENT_FILE: 'Import Student File',
  UP: 'UP',
  CLASS_ID: 'Class ID',
  SECTION_ID: 'Section ID',
  PARENT_ID: 'Parent ID',
  TEACHER_ID: 'Teacher ID',
  ROLE: 'Role',
  NO_IMPORTED_STUDENTS: 'No imported students.',
  CONFIRM_ACTION: 'Confirm Action',
  ACTION_CANNOT_BE_UNDONE: 'This action cannot be undone. Are you sure you want to continue?',
  DELETE_STUDENT: 'Delete Student',
  TEACHERS: 'Teachers',
  SUBJECT: 'Subject',
  EMPLOYEE_NO: 'Employee Number',
  HIRE_DATE: 'Hire Date',
  PROFILE: 'Profile',
  TEACHER_EMAIL: 'Teacher Email',
  EMPLOYEE_CODE: 'Employee Code',
  SPECIALIZATION: 'Specialization',
  EXPERIENCE_YEARS: 'Experience (Years)',
  CLASS_ASSIGNMENT: 'Class Assignment',
  ASSIGN_CLASS: 'Assign Class',
  NO_TEACHER_FOUND: 'No teachers found.',
};